const locations = [
    { name: "New York City, New York", folder: "nyc", message: "In the city that never sleeps, every moment with you felt like a dream. We wandered through the dazzling lights of Times Square, hand in hand, getting lost in the energy of it all. Central Park gave us a quiet escape, where we laughed, explored, and soaked in the beauty around us. Sailing past the Statue of Liberty, I couldn’t help but feel grateful for the adventure we were on together. Even at Starlight Diner, sharing a meal with Sanjana, there was something magical about the night—until I got sick. But even then, nothing could take away from the joy of being by your side. I’d relive every second of it, over and over again, just to be with you in our little corner of the city.", images: ["NYC1.JPG", "NYC2.JPG", "NYC3.JPG", "NYC4.JPG", "NYC5.JPG"], coords: [40.7128, -74.0060] },
    { name: "Cincinnati, Ohio", folder: "cincinnati", message: "Our time in Cincinnati was simple, but it was ours. Each morning, you left for work, and I stayed behind, working from our cozy little spot in bed—waiting for the moment you’d walk through the door again. That bed, as weak as it was, held us through lazy mornings and late-night conversations, even if it nearly gave out beneath us a few times. We cheered at the Reds game, the energy of the crowd wrapping around us, and later, we found peace in a quiet park, sharing a picnic and soaking in the warmth of summer. Those days may have been routine, but they were filled with the kind of love that makes even the smallest moments feel special.", images: ["cincinnati1.jpg", "cincinnati2.jpg", "cincinnati3.jpg", "cincinnati4.jpg", "cincinnati5.jpg"], coords: [39.1031, -84.5120] },
    { name: "Atlanta, Georgia", folder: "atlanta", message: "Atlanta will always be our city—not just because we live here, but because it’s where our story began. It’s where we met, where we had our first date, and where, somewhere between late-night talks and stolen glances, we fell in love. From pregames and frat parties to cozy dinners and buzzing bars, every corner of this city holds a memory of us. We’ve cheered at football games, danced through the streets, and braved hurricanes, snow days, and the kind of sweltering heat that makes you question everything. But through it all, we’ve had each other. No matter where life takes us, Atlanta will always be the place where it all started—where I found you.", images: ["atlanta1.jpg", "atlanta2.jpg", "atlanta3.jpg", "atlanta4.jpg", "atlanta5.jpg"], coords: [33.7490, -84.3880] },
    { name: "Louisville, Kentucky", folder: "louisville", message: "Louisville is more than just a city to me now—it’s a piece of you. The first time we visited, it was winter break, and I stepped into your world for the first time. I met your parents, your friends, your brother, and I saw the places that shaped the person I love. You showed me where you grew up, and with every story you told, I felt closer to you. When we came back in the summer, it felt like coming home. Staying at your parents' bed and breakfast, waking up to slow mornings and warm hospitality, I got to see Louisville through your eyes. Walking through the gardens of Old Louisville with your parents, I felt like I was becoming part of something bigger—your history, your family, your world. And nothing makes me happier than our double dates with your mom and stepdad, because it’s just another reminder that I belong here—with you.", images: ["louisville1.jpg", "louisville2.jpg", "louisville3.jpg", "louisville4.jpg", "louisville5.jpg"], coords: [38.2527, -85.7585] },
    { name: "New Orleans, Louisiana", folder: "neworleans", message: "New Orleans was wild, chaotic, and unforgettable—just like every adventure with you. You made me the perfect cooler, packed it with drinks, and we set off for a weekend that would become one of our craziest memories. We danced through Bourbon Street, the city lights and music wrapping around us, losing ourselves in the energy of the night. Formal itself was a blur of laughter, drinks, and stolen moments together. By the end of it, you were in my arms—maybe not in the way we planned, but in a way that reminded me how much I love taking care of you. I carried you home, watching over you while you slept, making sure you were safe. And somewhere between the parties and the chaos, we still found time for each other in the way only we could. New Orleans was messy, wild, and completely ours. (Minus Nico breaking his face.)", images: ["neworleans1.jpg", "neworleans2.jpg", "neworleans3.jpg", "neworleans4.jpg", "neworleans5.jpg"], coords: [29.9511, -90.0715] },
    { name: "Pigeon Forge, Tennessee", folder: "pigeonforge", message: "Tucked away in the mountains, surrounded by nothing but trees and stars, Pigeon Forge felt like our own little escape. Cabin Fever was wild in the best way—music blasting, drinks flowing, and a night full of dancing with you in my arms. We played endless rounds of Nickles, our laughter mixing with the chaos of the party, and when we needed a break, we slipped away to the pool, letting the warm water and cool mountain air wrap around us.But beyond the party, there was something special about just being there together—waking up to the quiet beauty of nature, sneaking little moments for ourselves between all the fun. No matter how crazy the night got, it always came back to you and me, and that’s what made it perfect.", images: ["pigeonforge1.jpg", "pigeonforge2.jpg", "pigeonforge3.jpg", "pigeonforge4.jpg", "pigeonforge5.jpg"], coords: [35.7884, -83.5543] },
    { name: "Panama City Beach, Florida", folder: "pcb", message: "Sun, sand, and a weekend that felt like pure summer. Beach Weekend was everything I could’ve wanted—good friends, football, and you by my side. We kicked things off at Chili’s, surrounded by the gang, cheering loud and proud (to hell with Georgia!), soaking in the perfect mix of rivalry and camaraderie. The beach was where we made the best memories. I made sure you were covered in sunscreen, carefully lathering every inch of you while you rolled your eyes and let me take care of you anyway. While I ran routes and played football in the sand, you and the other girlfriends built a sandcastle, laughing as the waves threatened to wash it away. It was one of those weekends where everything just felt right—the ocean breeze, the sunshine, and the feeling of being with you, completely happy in our little world. I'm so glad we managed to avoid the hurricane and enjoy it!", images: ["pcb1.jpg", "pcb2.jpg", "pcb3.jpg", "pcb4.jpg", "pcb5.jpg"], coords: [30.1766, -85.8055] }
];

const map = L.map('map').setView([37.0902, -95.7129], 5);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(map);

locations.forEach(location => {
    const marker = L.marker(location.coords).addTo(map);
    marker.bindPopup(`<b>${location.name}</b>`).on("click", () => {
        document.getElementById("location-text").textContent = location.message;
        const imageGallery = document.getElementById("image-gallery");
        imageGallery.innerHTML = ""; // Clear previous images

        location.images.forEach(img => {
            let imgElement = document.createElement("img");
            imgElement.src = `images/${location.folder}/${img}`;
            imgElement.alt = location.name;
            imageGallery.appendChild(imgElement);
        });
    });
});